### ISSUE TITLE
Refactor audit logs/webooks/django signals

### ISSUE THREAD

**Issue by dabeeeenster** [Flagsmith/flagsmith#272]
# The Problem

 * Currently the Audit Log is not generic enough meaning the creation of AuditLog records is implemented in different locations throughout the code. 
 * The AuditLog records only contain basic information about the change that was made - it doesn't hold any specifics about what was changed
 * We only audit certain entities in the platform. We need to be able to track all entities in the database. 

# The Solution

Some things to consider for the new AuditLog implementation:

 1. We want to centralise the creation of AuditLog records to a single location that can easily be implemented for new models and extended where necessary
 2. AuditLog records are important to us for triggering e.g. webhooks
 3. AuditLog records should be created using the task processor
 4. AuditLog records should contain more information about the change that was made. Currently the AuditLog only shows that a change was made to a given entity, it does not include any information about what was changed. 
 5. We need to make sure that the user is always captured with the AuditLog record (unless using a master API key)

# Questions to Answer

 1. We're currently using django-simple-history in certain models, but not all. Can we add this to all models and hook into it for the AuditLog? 
  a. What will this do to our database size? 
  b. Will this work for cases where we use BulkCreate / BulkUpdate ? Will we need to cater for these separately?
 2. Are there other packages we can use for this? Or should we write our own for easier extensibility?

**Comment by matthewelwell** [comment]
Current thought process: 

Create a base abstract model that implements django-simple-history. All models that we want to audit should inherit from that. We can then hook into a signal from the simple history models to create an audit log record in a one-to-one fashion (so that we can aggregate all history records). The AuditLog model would then implement properties (or methods on the relevant serializer) to display the data that we want to see. 

Concerns: 

 * This will work for changes made by a user but we will probably need to extend the history model class to allow us to set the master_api_key

**Comment by matthewelwell** [comment]
> Concerns:
> 
> * This will work for changes made by a user but we will probably need to extend the history model class to allow us to set the master_api_key

We should be able to achieve this by adding an additional field to the historical model, using the following: 

https://django-simple-history.readthedocs.io/en/latest/historical_model.html#adding-additional-fields-to-historical-models
