### ISSUE TITLE
Keep a versioned record of all Flag States

### ISSUE THREAD

**Issue by dabeeeenster** [Flagsmith/flagsmith#303]
## Overview 

We should keep a versioned record of all Flag States in the `features_featurestate` and `features_featurestatevalue` tables. This will enable features to:

1. Be able to see a version history of a flag along with what was changed and by whom
2. Be able to power 4-eyes changes as per #199 

## Approach

Create a new column in `features_featurestate` called `version`. This is either an incrementing integer (denoting an older version of the database row) or `-1` (denoting the live version).

Create a new column in `features_featurestate` that joins the row with `users_ffadminuser` so that we can track who made edits to that version of the flag. 

## Conflict Resolution

Simply: last write wins. 

## Changes to existing platform

ALL queries apart from viewing a flag's history should include `AND features_featurestate.version = -1` or similar. 

Create a new endpoint to get the version history for a particular flag. 

Add a UI component to the flag modal to allow the user to view the version history of the flag. 

## Tying in to 4 eyes approval

Store a version of the `features_featurestate` that contains the data of the flag state that is awaiting approval. Approval is then just a matter of swapping the version number with the live version number `-1`

**Comment by matthewelwell** [comment]
Some things to consider: 

 * We currently use the HistoricalFeatureState object for webhooks. We'll need to consider this when implementing the new version engine since we'll be creating records for drafts that we obviously don't want. Can we prevent the historical record being created until a FeatureState becomes 'COMMITTED'? Do we care given that we're probably going to remove HistoricalFeatureState after this change?
 * Do we want to worry about creating versions of feature states for old HistoricalFeatureState objects?

**Comment by matthewelwell** [comment]
@dabeeeenster do we want to be able to schedule / enforce 4 eyes on feature states that are associated with an identity / feature segment (aka identity / segment overrides)?

**Comment by dabeeeenster** [comment]
> @dabeeeenster do we want to be able to schedule / enforce 4 eyes on feature states that are associated with an identity / feature segment (aka identity / segment overrides)?

Segments: yes
Identities not as important for now

**Comment by matthewelwell** [comment]
Resolved by #794.
