### ISSUE TITLE
Use of Mysql  as database

### ISSUE THREAD

**Issue by giddel** [Flagsmith/flagsmith#39]
Is it possible to use a Mysql database instead of Postgres? 
If not - what are the main Todo's to enable it?

**Comment by matthewelwell** [comment]
Hi @giddel, it should totally be possible to use MySQL as a database as we're not currently using any of the custom Postgres fields. In fact, we used to run it on MySQL ourselves. 

It hasn't been tested in a while on MySQL however, so let me know if you have any problems.

**Comment by giddel** [comment]
That sounds really good :-)
I'll check that out in the next days. Thanks!

**Comment by thccorni** [comment]
I did a quick test starting the api locally with mysql (via docker-compose).

I encountered problems with two of the migrations:

1. https://github.com/BulletTrainHQ/bullet-train-api/blob/65423c06de4d008346d2ce330f84baf5a94b4b72/src/organisations/migrations/0014_userorganisation.py#L10
2. https://github.com/BulletTrainHQ/bullet-train-api/blob/65423c06de4d008346d2ce330f84baf5a94b4b72/src/features/migrations/0005_auto_20180604_1348.py#L19

The first one seems to be an issue with the double quotes which should be an easy fix.

For the second one it seems that mysql does not like the `lower` function in the unique index. I'm not sure how to fix this. Maybe @matthewelwell has a suggestion?

**Comment by matthewelwell** [comment]
Hey @thccorni. Thanks for this information - very useful!

Yes, it looks like MySQL doesn't support the use of transformation functions in unique keys. The best solution is probably to alter the code so that feature names are stored as lower case and just have the unique index on name, project_id (which could then just be done in the django model). I'll add this to our backlog of things to look at. 

A quick solution to get it working with mysql in the short term would be to update the collation on the `name` column of the `features_feature` table to be case insensitive and then change that migration to create a unique index on `(name, project_id)`. 

Reference: https://stackoverflow.com/questions/6888279/is-there-any-way-to-make-a-unique-index-case-insensitive-in-mysql-5-1-x/6888308
